blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è³ªå•ãƒ»ç›¸è«‡
    url: https://github.com/bi9dri/side-oripathy/discussions
    about: ãƒã‚°ã‚„æ©Ÿèƒ½è¦æœ›ä»¥å¤–ã®ã”è³ªå•ãƒ»ã”ç›¸è«‡ã¯Discussionsã‚’ã”åˆ©ç”¨ãã ã•ã„
